-- RUN THIS SCRIPT IN YOUR SUPABASE SQL EDITOR

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,  -- Will store hashed password
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Resumes Table
CREATE TABLE IF NOT EXISTS public.resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id),
    file_name TEXT,
    role_target TEXT,
    upload_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    extracted_data JSONB, -- Stores skills, summary, etc.
    matches JSONB         -- Stores job matches
);

-- 3. Create Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT,
    location TEXT,
    required_skills TEXT[], 
    tags TEXT[],
    icon TEXT,
    description TEXT
);

-- 4. Enable Row Level Security (Recommended but optional initially)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Allow public access for now for simplicity, tighten later)
CREATE POLICY "Public users are viewable by everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public users can perform insert" ON public.users FOR INSERT WITH CHECK (true);

CREATE POLICY "Public resumes are viewable by everyone" ON public.resumes FOR SELECT USING (true);
CREATE POLICY "Public resumes can perform insert" ON public.resumes FOR INSERT WITH CHECK (true);

CREATE POLICY "Public jobs are viewable by everyone" ON public.jobs FOR SELECT USING (true);
CREATE POLICY "Public jobs can perform insert" ON public.jobs FOR INSERT WITH CHECK (true);


-- 6. Insert Mock Data (Optional)
INSERT INTO public.jobs (title, company, location, required_skills, tags, icon) VALUES
('Frontend Developer', 'TechCorp', 'Remote', ARRAY['React', 'JavaScript', 'CSS'], ARRAY['Remote'], '💻'),
('Backend Engineer', 'DataSystems', 'NY', ARRAY['Node.js', 'Express', 'SQL'], ARRAY['Backend'], '⚙️');

-- 7. Saved Jobs Table
CREATE TABLE IF NOT EXISTS public.saved_jobs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id),
    job_title TEXT,
    company TEXT,
    location TEXT,
    saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public saved_jobs are viewable by everyone" ON public.saved_jobs FOR SELECT USING (true);
CREATE POLICY "Public saved_jobs can perform insert" ON public.saved_jobs FOR INSERT WITH CHECK (true);
